version: "4.13"

x-common-variables: &common-variables
  MYSQL_USER: testikayttaja
  MYSQL_PASSWORD: 1testisalasana2!
  MYSQL_DATABASE: sampledb
  REACT_APP_SERVER_PORT: 8000

#define which docker images should be used/built
#introduce env variables, designate ports etc.
services:

  mysql-db:
    image: mysql:latest
    # Comment next line if running on Intel/AMD machine
    platform: linux/arm64/v8
    container_name: mysql-db-container
    # TODO: figure out authentication issue between versions.
    # This line allows the use of native db login
    command: --default-authentication-plugin=mysql_native_password
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    # Mount db population script into the container.
    # Scripts in /docker-entrypoint-initdb.d/init.sql are run automatically when db is initialized
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
  # defines dependency to above mysq-db - will not start before it
    depends_on:
      - mysql-db
    image: phpmyadmin:latest
    platform: linux/arm64/v8
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always

  client:
    build: ./client
    container_name: react_client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    command: npm start
  