name: Test

on:
  push:
    branches:
    - main
    - features/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Collect docker logs on failure
      if: "!success()"
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs-docs'
        
    - name: Upload logs to GitHub
      if: "!success()"
      uses: actions/upload-artifact@main
      with:
        name: logs-docs.tgz
        path: ./logs/logs-docs.tgz

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

